### ISSUE TITLE
Missing dependencies and files

### ISSUE THREAD

**Issue by WinGDKoni** [dblock/waffle#254]
In file Source\ThirdParty\maven-install.cmd the mvn call is commented out. Still needed? If I use that call, I get an error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install-file (default-cli) on project standalone-pom: The specified file 'C:\Data\Source\github.com\waffle\Source\ThirdParty\spring-security\spring-security-core-4.0.2.RELEASE.jar' not exists -> [Help 1]

The Visual Studio project references a missing file:
FileName: GlobalAssemblyInfo.cs
PathOnDisk: C:\Data\Source\github.com\waffle\Source\Common\GlobalAssemblyInfo.cs
PathInVisualStudio: Solution\WindowsAuthProvider\Properties\GlobalAssemblyInfo.cs

**Comment by hazendaz** [comment]
For Java piece, the call is commented out and nothing more than an example in case we need it again.  See beginning text in the file that reads -> ':: example '.  We used that as a delivery tool when we supported tomcat 5 versions not readily available in maven central and for spring security 4 before it was officially released.  If we happen to still document this usage in the readme's, I'll work to clean those up.  I also feel we won't need this again and have a better solution at this point so I will work to remove this entirely.  Please let me know where all you might have seen info on this with the project.  Thanks.

For GlobalAssemblyInfo, the file is in gitignore.  It's auto generated.  There is a hook to keep the directory in git.  I'm not a .net expert so not sure if this is intentional behaviour.  @dblock thoughts?

**Comment by WinGDKoni** [comment]
In the file SettingUpDevelopmentEnvironment.md I was reading:

Third Party (Non Maven Central Items)
After maven is installed, go into  Source/ThirdParty  and run  maven-install.cmd . This will install third party dependencies needed for building that are not available in maven central. This is done to allow us to avoid using system scope dependencies.

Should then that section be removed or changed?

The missing files got generated.

Thanks

**Comment by hazendaz** [comment]
Thanks.  Plan is to remove that info.  If we ever need to do that again I have an automatic maven way to do the same.


Sent by Outlook for Android





On Thu, Oct 15, 2015 at 1:21 AM -0700, "WinGDKoni" <notifications@github.com> wrote:
In the file SettingUpDevelopmentEnvironment.md I was reading:

Third Party (Non Maven Central Items)
After maven is installed, go into  Source/ThirdParty  and run  maven-install.cmd . This will install third party dependencies needed for building that are not available in maven central. This is done to allow us to avoid using system scope dependencies.

Should then that section be removed or changed?

The missing files got generated.

Thanks



---

**Comment by hazendaz** [comment]
All the info on third party on the java side has been removed.  @WinGDKoni can you tell me if everything is ok when trying to build with .net?  If so, I'll close this out.

Thanks,

Jeremy

**Comment by WinGDKoni** [comment]
Yes. Please close.

**Comment by hazendaz** [comment]
Thank you!
