### ISSUE TITLE
Is there Kerberos LoginModule for JAAS in WAFFLE?

### ISSUE THREAD

**Issue by bacar** [dblock/waffle#302]
Is there a Kerberos LoginModule for JAAS in WAFFLE - similar to the quest VSJ com.dstc.security.kerberos.winsspi.WinSSPILoginModule ?

i.e. something I can stick in my jaas.conf of my java client running on windows, that will allow it to authenticate automatically with e.g. SPNEGO services using HttpUrlConnection.

**Comment by dblock** [comment]
Yes, Waffle has a JAAS module, see https://github.com/dblock/waffle/blob/master/Docs/tomcat/TomcatWindowsLoginJAASAuthenticator.md.

Please use the [mailing list](http://groups.google.com/group/waffle-users) to ask questions.

**Comment by cebaa** [comment]
> Please use the mailing list to ask questions.

I know it's slightly annoying to you guys (i.e. devs), but it's not possible to access google groups sometimes for various reasons... It is perhaps better to at least voice the need using a ticket than not hearing from the users.

The JAAS LoginModue that is provided does not use SSPI though, but username and password. It might be a good idea to re-open this ticket (or create a new one - happy to do it if you think it would be useful) with a new-feature tag with the goal of implementing a SSPI-backed LoginModule. My impression is that that's the end goal of majority of users using Waffle - i.e. a complete SSO, without the need to supply username and password.

**Comment by dblock** [comment]
@cebaa You're raising a different or tangent issue that definitely deserves a feature request here. The OP was asking whether a JAAS module existed... the answer was yes :)

**Comment by cebaa** [comment]
@dblock I've created a new ticket as you suggested https://github.com/Waffle/waffle/issues/773.

**Comment by hazendaz** [comment]
Hi, sorry there isnt a lot of activity on waffle.  Since its windows only it doesnt have a larger community backing.  I'm maintaining it but mostly just that.  All the production systems I use are linux.  So outside of someone responding on the waffle user group some tickets wont get fast action.  However if you are able to build missing support it will get quick release.

Thanks

Jeremy

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
